### ISSUE TITLE
IndexOutOfBoundsException with maxLength set 

### ISSUE THREAD

**Issue by Abbo44** [hootsuite/nachos#32]
Hi Hootsuite, 

First of all, congrats about your amazing job ! Really useful library who save me a lot of work !

I have an issue with the maxLength paramater in NachoTextView which is not working 

```java
java.lang.IndexOutOfBoundsException: setSpan (201 ... 201) ends beyond length 200
                                                                           at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1100)
                                                                           at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:675)
                                                                           at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:668)
                                                                           at android.text.Selection.setSelection(Selection.java:76)
                                                                           at android.text.Selection.setSelection(Selection.java:87)
                                                                           at android.widget.EditText.setSelection(EditText.java:98)
                                                                           at com.hootsuite.nachos.NachoTextView.handleTextChanged(NachoTextView.java:858)
                                                                           at com.hootsuite.nachos.NachoTextView.afterTextChanged(NachoTextView.java:826)
```
Below my layout 
```xml
 <android.support.design.widget.TextInputLayout
                android:id="@+id/upload_keywords_layout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:counterEnabled="true"
                app:counterMaxLength="200">

                <com.hootsuite.nachos.NachoTextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:maxLength="200" />

</android.support.design.widget.TextInputLayout>
```

```java
mNachoTextView.addChipTerminator(' ', ChipTerminatorHandler.BEHAVIOR_CHIPIFY_CURRENT_TOKEN);
```
When a token is chipified, there are 3 characters which are created too. Is it a normal behaviour ? Because it's why I have an IndexOutOfBoundsException, if you add 3 more characters on the chips creation, and if I have a maxLength on the view

Thank you,
Abbo

**Comment by Abbo44** [comment]
Well, when a token is chipified, there are 3 characters which are created too. Tha's a normal behaviour ? Because it's why I have an IndexOutOfBoundsException, if you add 3 more characters on the chips creation

**Comment by Abbo44** [comment]
Ok so I found the solution, it's the behavior of ChipTerminatorHandler.BEHAVIOR_CHIPIFY_CURRENT_TOKEN.
I changed it to ChipTerminatorHandler.BEHAVIOR_CHIPIFY_TO_TERMINATOR, and no more 3 characters :).

Thank you,
Abbo
